# Generated by Django 4.2.14 on 2024-12-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SectionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название раздела')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название элемента')),
                ('preview', models.TextField(default='', max_length=200, verbose_name='Превью текст')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image1', models.ImageField(upload_to='projects/media/', verbose_name='Превью')),
                ('image2', models.ImageField(upload_to='projects/media/', verbose_name='Картинка в элементе')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('title1', models.TextField(verbose_name='Блок 1 с информацией - заголовок')),
                ('text1', models.TextField(verbose_name='Блок 1 с информацией - текст')),
                ('title2', models.TextField(verbose_name='Блок 2 с информацией - заголовок')),
                ('text2', models.TextField(verbose_name='Блок 2 с информацией - текст')),
                ('title3', models.TextField(verbose_name='Блок 3 с информацией - заголовок')),
                ('text3', models.TextField(verbose_name='Блок 3 с информацией - текст')),
                ('img_back', models.ImageField(upload_to='projects/media/', verbose_name='Картинка на фон')),
                ('service', models.TextField(verbose_name='Услуги')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('text_teblet', models.TextField(verbose_name='Текст для блока Tablet версия')),
                ('pres_title', models.TextField(verbose_name='Заголовок для презентации')),
                ('pres_text', models.TextField(verbose_name='Текст презентации')),
                ('shadow', models.ImageField(upload_to='projects/media/', verbose_name='Фон на баннере')),
                ('block1_html', models.TextField(verbose_name='Блок 1 html')),
                ('block2_txt', models.TextField(verbose_name='Desktop версия ТЕКСТ')),
                ('block2_html', models.TextField(verbose_name='Блок 2 html')),
                ('block3_html', models.TextField(verbose_name='Блок 3 html')),
                ('block4_html', models.TextField(verbose_name='Блок 4 html')),
                ('title4', models.TextField(verbose_name='Блок 4 с информацией - заголовок')),
                ('text4', models.TextField(verbose_name='Блок 4 с информацией - текст')),
                ('block5_html', models.TextField(verbose_name='Блок 5 html')),
                ('block6_html', models.TextField(verbose_name='Блок 6 html')),
                ('img_laptop', models.ImageField(upload_to='projects/media/', verbose_name='Картинка ноутбук')),
                ('industries', models.ManyToManyField(to='projects.industry')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.sectionproject')),
                ('type', models.ManyToManyField(to='projects.type')),
            ],
        ),
    ]
