# Generated by Django 4.2.14 on 2024-12-26 12:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок блока')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст блока')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'Мобильная версия'), ('desktop', 'Компьютерная версия'), ('tablet', 'Планшетная версия'), ('presentation', 'Презентация')], max_length=50, verbose_name='Тип слайдера')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/sliders', verbose_name='Картинка слайдера')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.slider', verbose_name='Слайдер')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='block1_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block2_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block2_txt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block3_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block4_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block5_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block6_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_back',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_laptop',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pres_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pres_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='preview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shadow',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text_teblet',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title4',
        ),
        migrations.AddField(
            model_name='project',
            name='additional_intro_field',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Доп. вводное поле'),
        ),
        migrations.AddField(
            model_name='project',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Картинка на фон'),
        ),
        migrations.AddField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Картинка на баннере'),
        ),
        migrations.AddField(
            model_name='project',
            name='element_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Картинка в элементе'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_image',
            field=models.ImageField(default=1, upload_to='projects/images/', verbose_name='Картинка вводного текста'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='intro_text',
            field=models.TextField(default=1, verbose_name='Вводный текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Выводить в общий список'),
        ),
        migrations.AddField(
            model_name='project',
            name='laptop_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Картинка на ноутбуке'),
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст презентации'),
        ),
        migrations.AddField(
            model_name='project',
            name='presentation_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок презентации'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industries',
            field=models.ManyToManyField(to='projects.industry', verbose_name='Отрасли'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Тип сайта'),
        ),
        migrations.DeleteModel(
            name='SectionProject',
        ),
        migrations.AddField(
            model_name='slider',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='descriptionblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_blocks', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(to='projects.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
