# Generated by Django 4.2.14 on 2024-12-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='select_on_main',
            field=models.BooleanField(default=1, verbose_name='Выводить в блоке на главной'),
            preserve_default=False,
        ),
    ]
