# Generated by Django 4.2.14 on 2024-12-25 08:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_select_on_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_slider', models.ImageField(upload_to='imgs/', verbose_name='Картинка в слайдер')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Сортировка')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='block2_txt',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text4',
        ),
        migrations.AddField(
            model_name='project',
            name='other',
            field=models.ManyToManyField(blank=True, null=True, to='projects.project', verbose_name='Другие проекты'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block1_html',
            field=ckeditor.fields.RichTextField(verbose_name='Блок 1 html'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block2_html',
            field=ckeditor.fields.RichTextField(verbose_name='Блок 2 html'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block3_html',
            field=ckeditor.fields.RichTextField(verbose_name='Блок 3 html'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block4_html',
            field=ckeditor.fields.RichTextField(verbose_name='Блок 4 html'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block5_html',
            field=ckeditor.fields.RichTextField(verbose_name='Блок 5 html'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block6_html',
            field=ckeditor.fields.RichTextField(verbose_name='Блок 6 html'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(upload_to='imgs/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(upload_to='imgs/', verbose_name='Картинка в элементе'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_back',
            field=models.ImageField(upload_to='imgs/', verbose_name='Картинка на фон'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img_laptop',
            field=models.ImageField(upload_to='imgs/', verbose_name='Картинка ноутбук'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='service',
        ),
        migrations.AlterField(
            model_name='project',
            name='shadow',
            field=models.ImageField(upload_to='imgs/', verbose_name='Фон на баннере'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('mobile', "Слайдер 'телефон'"), ('desktop', "Слайдер 'компьютер'"), ('tablet', "Слайдер 'tablet'"), ('presentation', 'Слайдер презентация')], max_length=20, null=True)),
                ('img_slider', models.ManyToManyField(to='projects.imgsslider')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='slider',
            field=models.ManyToManyField(to='projects.slider'),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ManyToManyField(to='projects.service'),
        ),
    ]
