# Generated by Django 4.2.14 on 2024-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_descriptionblock_service_slider_sliderimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptionblock',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Положение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='other_projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.project', verbose_name='Другие проекты'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Положение'),
            preserve_default=False,
        ),
    ]
