# Generated by Django 4.2.14 on 2024-12-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_imgsslider_service_remove_project_block2_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title1',
            field=models.CharField(max_length=200, verbose_name='Блок 1 с информацией - заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title2',
            field=models.CharField(max_length=200, verbose_name='Блок 2 с информацией - заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title3',
            field=models.CharField(max_length=200, verbose_name='Блок 3 с информацией - заголовок'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title4',
            field=models.CharField(max_length=200, verbose_name='Блок 4 с информацией - заголовок'),
        ),
    ]
