# Generated by Django 4.2.14 on 2024-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_descriptionblock_order_project_other_projects_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionblock',
            options={'verbose_name': 'Блок описания', 'verbose_name_plural': 'Блоки описания'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Отрасль', 'verbose_name_plural': 'Отрасли'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name': 'Картинка слайдера', 'verbose_name_plural': 'Картинки слайдера'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterField(
            model_name='descriptionblock',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Положение'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Положение'),
        ),
        migrations.AlterUniqueTogether(
            name='slider',
            unique_together={('project', 'type')},
        ),
    ]
