# Generated by Django 4.2.14 on 2024-12-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_title1_alter_project_title2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pres_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок для презентации'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview',
            field=models.CharField(default='', max_length=200, verbose_name='Превью текст'),
        ),
    ]
