# Generated by Django 4.2.14 on 2024-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_descriptionblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='project',
            name='select_on_main',
            field=models.BooleanField(default=False, verbose_name='Выводить в блоке на главной?'),
        ),
    ]
