# Generated by Django 4.2.14 on 2024-12-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_link_project_select_on_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptionblock',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Положение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_intro_field',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вводное описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro_image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='Картинка в списке объектов'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Положение'),
        ),
        migrations.AlterUniqueTogether(
            name='descriptionblock',
            unique_together={('project', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='sliderimage',
            unique_together={('slider', 'order')},
        ),
    ]
