# Generated by Django 4.2.14 on 2024-12-26 12:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_link_alter_project_pres_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Название блока')),
                ('text', ckeditor.fields.RichTextField(null=True, verbose_name='Блок html')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='block1_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block2_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block3_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block4_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block5_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='block6_html',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title4',
        ),
        migrations.DeleteModel(
            name='SectionProject',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moderation', to='projects.project', verbose_name='Блоки для проектов'),
        ),
    ]
