# Generated by Django 4.2.14 on 2025-01-15 07:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_descriptionblock_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main', 'Основной'), ('mobile', 'Мобильная версия'), ('desktop', 'Компьютерная версия'), ('tablet', 'Планшетная версия'), ('presentation', 'Презентация')], max_length=50, verbose_name='Тип слайдера')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок блока')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст блока')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'unique_together': {('project', 'type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='slider',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='slider',
            name='project',
        ),
        migrations.DeleteModel(
            name='DescriptionBlock',
        ),
        migrations.AlterUniqueTogether(
            name='sliderimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.block', verbose_name='Слайдер'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sliderimage',
            unique_together={('block', 'order')},
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='slider',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
