# Generated by Django 4.2.14 on 2025-01-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_block_alter_slider_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
