# Generated by Django 4.2.14 on 2025-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_block_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['order'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='presentation_text',
        ),
        migrations.RemoveField(
            model_name='project',
            name='presentation_title',
        ),
        migrations.AddField(
            model_name='block',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/images/', verbose_name='Изображение блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Положение'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('project', 'order')},
        ),
        migrations.RemoveField(
            model_name='block',
            name='type',
        ),
    ]
