# Generated by Django 4.2.14 on 2025-01-30 06:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_block_options_alter_block_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Изображение блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст блока'),
        ),
    ]
