# Generated by Django 4.2.14 on 2025-04-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_block_image_alter_block_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='type_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.type', verbose_name='Тип (устаревший)'),
        ),
        migrations.AddField(
            model_name='project',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.type', verbose_name='Типы'),
        ),
    ]
