# Generated by Django 4.2.14 on 2025-04-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_type_project_type_old_project_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type_old',
        ),
    ]
