# Generated by Django 4.2.14 on 2025-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.TextField(default=111, verbose_name='Описание на главной'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='select_on_main',
            field=models.BooleanField(default=False, verbose_name='Выводить в блоке на главной?'),
        ),
    ]
