# Generated by Django 4.2.14 on 2025-04-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_type_description_type_select_on_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='types',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.type', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
