# Generated by Django 4.2.14 on 2025-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_project_types_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['order_on_main'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AddField(
            model_name='type',
            name='order_on_main',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Положение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='select_on_main',
            field=models.BooleanField(default=False, verbose_name='Выводить в блоке на главной'),
        ),
    ]
