# Generated by Django 4.2.14 on 2025-04-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_type_options_type_order_on_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/', verbose_name='Изображение на фон'),
        ),
        migrations.AlterField(
            model_name='project',
            name='element_image',
            field=models.ImageField(blank=True, help_text='На странице объекта, на баннере', null=True, upload_to='projects/images/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro_image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='Изображение в списке объектов'),
        ),
        migrations.AlterField(
            model_name='type',
            name='order_on_main',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Положение на главной'),
        ),
        migrations.AlterField(
            model_name='type',
            name='select_on_main',
            field=models.BooleanField(default=False, verbose_name='Выводить в блоке на главной'),
        ),
    ]
