# Generated by Django 4.2.14 on 2025-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='additional_intro_field',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro_text',
            field=models.CharField(verbose_name='Вводный текст'),
        ),
    ]
