# Generated by Django 4.2.14 on 2025-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_additional_intro_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Положение'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('order',)},
        ),
    ]
