# Generated by Django 4.2.14 on 2025-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_unique_together_alter_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='Положение'),
            preserve_default=False,
        ),
    ]
