# Generated by Django 4.2.14 on 2024-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='Как к вам обращаться? ')),
                ('phone', models.CharField(default='', max_length=17, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=40, verbose_name='E-mail')),
                ('product', models.TextField(verbose_name='Какой продукт вам нужен?')),
                ('budget', models.TextField(verbose_name='Бюджет проекта')),
                ('project_descr', models.CharField(max_length=300, verbose_name='Почему пользователи должны сделать выбор в вашу пользу, а не в пользу конкурентов? ')),
                ('url_competitors', models.CharField(max_length=300, verbose_name='Ссылки на ваших основных конкурентов ')),
                ('url_same_like', models.CharField(max_length=300, verbose_name='Примеры сайтов по схожей тематике с вашей, которые вам нравятся. Напишите, что нравится на этих сайтах ')),
                ('url_same_dislike', models.CharField(max_length=300, verbose_name='Примеры сайтов по схожей тематике с вашей, которые вам не нравятся. Напишите, что не нравится на этих сайтах ')),
                ('price', models.CharField(max_length=300, verbose_name='Насколько конкурентна цена на ваш продукт или услугу? И из чего формируется эта цена? ')),
                ('repulsive_impression', models.CharField(max_length=300, verbose_name='Что всегда производит на клиентов отталкивающее впечатление? ')),
                ('important', models.CharField(max_length=300, verbose_name='Критерии, то что ВАЖНО. 5 вещей, на которые он будет смотреть при выборе подрядчика. Или открыв 5 сайтов ваших конкурентов? ')),
                ('target', models.CharField(max_length=300, verbose_name='Что именно вашей целевой аудитории нравится в ваших конкурентах? ')),
                ('problems', models.CharField(max_length=300, verbose_name='1-3 ключевых боли? Проблемы, которые мешают человеку в повседневности, и которые вы можете частично или полностью решить вашим продуктом? ')),
                ('triggers', models.CharField(max_length=300, verbose_name='Триггеры? Какая тема его неосознанно зацепит, хочет он того или нет? Обычно это что-то простое, мимо чего он не может пройти. ')),
                ('info_pain', models.CharField(max_length=300, verbose_name='Инфоболь? Информационная боль - это вынужденный поиск информации пользователем в Интернете для решения своей проблемы. Что они гуглят? ')),
                ('needs', models.CharField(max_length=300, verbose_name='Потребности? Зачем ему потребовалось покупать (опишите ситуацию)? Что он хочет получить в итоге, какой результат? ')),
                ('barriers', models.CharField(max_length=300, verbose_name='Опишите минимум 30 барьеров, на которые вы можете как-то повлиять: от важных до самых пустяковых, почему ЦА сомневается в покупке? В том числе опишите этап после покупки - возможно он боится, что через год все сломается. Что может помешать купить вашу услугу? ')),
                ('look_for', models.CharField(max_length=300, verbose_name='К чему стремятся при выборе продукта/услуги? ')),
                ('design', models.CharField(max_length=300, verbose_name='Какое впечатление должен, на Ваш взгляд, создавать дизайн лендинга? ')),
                ('associations', models.CharField(max_length=300, verbose_name='Какие ассоциации должен вызывать дизайн? (например нежный, легкий, воздушный) ')),
                ('main_segment', models.CharField(max_length=300, verbose_name='Основной сегмент целевой аудитории? на кого приходится 80% продаж? ')),
            ],
            options={
                'verbose_name': 'Заявка "Брифинг"',
                'verbose_name_plural': 'Заявки "Брифинг"',
            },
        ),
        migrations.CreateModel(
            name='NewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, verbose_name='Как к вам обращаться? ')),
                ('phone', models.CharField(default='', max_length=17, verbose_name='Номер для связи')),
                ('communications', models.TextField(verbose_name='Способ связи')),
                ('budget', models.TextField(verbose_name='Бюджет проекта')),
                ('project_descr', models.TextField(verbose_name='Опишите проект ')),
                ('promocode', models.CharField(max_length=40, verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заявка "Обсудить проект"',
                'verbose_name_plural': 'Заявки "Обсудить проект"',
            },
        ),
    ]
