# Generated by Django 4.2.14 on 2024-12-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefing',
            name='important',
        ),
        migrations.AddField(
            model_name='briefing',
            name='advantages',
            field=models.CharField(default=1, max_length=300, verbose_name='Преимущества'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='briefing',
            name='main_info',
            field=models.CharField(default=1, max_length=300, verbose_name='Необходимая информация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='briefing',
            name='purpose',
            field=models.CharField(default=1, max_length=300, verbose_name='Цели сайта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='briefing',
            name='target_audience',
            field=models.CharField(default=1, max_length=300, verbose_name='Целевая аудитория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='briefing',
            name='сriteria',
            field=models.CharField(default=1, max_length=300, verbose_name='Критерии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='briefing',
            name='associations',
            field=models.CharField(max_length=300, verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='barriers',
            field=models.CharField(max_length=300, verbose_name='Барьеры'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='design',
            field=models.CharField(max_length=300, verbose_name='Впечатление'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='Как обращаться'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='info_pain',
            field=models.CharField(max_length=300, verbose_name='Инфоболь'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='look_for',
            field=models.CharField(max_length=300, verbose_name='Цель при выборе продукта'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='main_segment',
            field=models.CharField(max_length=300, verbose_name='Основной сегмент ЦА'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='needs',
            field=models.CharField(max_length=300, verbose_name='Потребности'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='price',
            field=models.CharField(max_length=300, verbose_name='Основа для формирования цен'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='problems',
            field=models.CharField(max_length=300, verbose_name='Проблемы'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='product',
            field=models.TextField(verbose_name='Какой продукт нужен'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='project_descr',
            field=models.CharField(max_length=300, verbose_name='Описание проекта в основных чертах'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='repulsive_impression',
            field=models.CharField(max_length=300, verbose_name='Отталкивающее клиентов'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='target',
            field=models.CharField(max_length=300, verbose_name='Сильные стороны конкурентов'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='triggers',
            field=models.CharField(max_length=300, verbose_name='Триггеры'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='url_competitors',
            field=models.CharField(max_length=300, verbose_name='Ссылки на конкурентов'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='url_same_dislike',
            field=models.CharField(max_length=300, verbose_name='Плохие сайты'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='url_same_like',
            field=models.CharField(max_length=300, verbose_name='Нравящиеся сайты'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='fio',
            field=models.CharField(max_length=40, verbose_name='Как обращаться'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='project_descr',
            field=models.TextField(verbose_name='Описание проекта'),
        ),
    ]
