# Generated by Django 4.2.14 on 2024-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_briefing_important_briefing_advantages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='budget',
            field=models.CharField(max_length=300, verbose_name='Бюджет проекта'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='product',
            field=models.CharField(max_length=300, verbose_name='Какой продукт нужен'),
        ),
    ]
