# Generated by Django 4.2.14 on 2024-12-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_briefing_budget_alter_briefing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefing',
            name='advantages',
            field=models.TextField(max_length=300, verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='associations',
            field=models.TextField(max_length=300, verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='barriers',
            field=models.TextField(max_length=300, verbose_name='Барьеры'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='design',
            field=models.TextField(max_length=300, verbose_name='Впечатление'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='info_pain',
            field=models.TextField(max_length=300, verbose_name='Инфоболь'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='look_for',
            field=models.TextField(max_length=300, verbose_name='Цель при выборе продукта'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='main_info',
            field=models.TextField(max_length=300, verbose_name='Необходимая информация'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='main_segment',
            field=models.TextField(max_length=300, verbose_name='Основной сегмент ЦА'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='needs',
            field=models.TextField(max_length=300, verbose_name='Потребности'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='price',
            field=models.TextField(max_length=300, verbose_name='Основа для формирования цен'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='problems',
            field=models.TextField(max_length=300, verbose_name='Проблемы'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='project_descr',
            field=models.TextField(max_length=300, verbose_name='Описание проекта в основных чертах'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='repulsive_impression',
            field=models.TextField(max_length=300, verbose_name='Отталкивающее клиентов'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='target',
            field=models.TextField(max_length=300, verbose_name='Сильные стороны конкурентов'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='target_audience',
            field=models.TextField(max_length=300, verbose_name='Целевая аудитория'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='triggers',
            field=models.TextField(max_length=300, verbose_name='Триггеры'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='url_competitors',
            field=models.TextField(max_length=300, verbose_name='Ссылки на конкурентов'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='url_same_dislike',
            field=models.TextField(max_length=300, verbose_name='Плохие сайты'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='url_same_like',
            field=models.TextField(max_length=300, verbose_name='Нравящиеся сайты'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='сriteria',
            field=models.TextField(max_length=300, verbose_name='Критерии'),
        ),
    ]
