# Generated by Django 4.2.14 on 2024-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_briefing_advantages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='promocode',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Промокод'),
        ),
    ]
