# Generated by Django 4.2.14 on 2024-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_newproject_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='email',
            field=models.CharField(default=1, max_length=40, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newproject',
            name='telegram_name',
            field=models.CharField(default=1, max_length=40, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='briefing',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='communications',
            field=models.TextField(choices=[('call', 'Звонок'), ('email', 'Почта'), ('telegram', 'Телеграм')], verbose_name='Способ связи'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Номер для связи'),
        ),
    ]
