# Generated by Django 4.2.14 on 2024-12-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_newproject_email_newproject_telegram_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproject',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='telegram_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Telegram'),
        ),
    ]
