# Generated by Django 4.2.14 on 2025-01-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_newproject_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=17, verbose_name='Номер телефона')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Заявка "Обратная связь"',
                'verbose_name_plural': 'Заявки "Обратная связь"',
            },
        ),
    ]
