# Generated by Django 4.2.14 on 2025-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproject',
            name='communications',
        ),
        migrations.RemoveField(
            model_name='newproject',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='newproject',
            name='telegram_name',
        ),
        migrations.AlterField(
            model_name='briefing',
            name='associations',
            field=models.TextField(max_length=300, verbose_name='Впечатление'),
        ),
        migrations.AlterField(
            model_name='briefing',
            name='design',
            field=models.TextField(max_length=300, verbose_name='Дизайн'),
        ),
        migrations.AlterField(
            model_name='newproject',
            name='email',
            field=models.CharField(default=1, max_length=40, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
