# Generated by Django 4.2.14 on 2025-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_remove_newproject_communications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproject',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='newproject',
            name='type_of_product',
            field=models.TextField(default=1, verbose_name='Тип продукта'),
            preserve_default=False,
        ),
    ]
