# Generated by Django 4.2.14 on 2025-01-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='infoblock',
            unique_together={('vacancy', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('vacancy', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='responsibility',
            unique_together={('vacancy', 'order')},
        ),
    ]
