# Generated by Django 4.2.14 on 2025-01-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_infoblock_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио')),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл с портфолио')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'unique_together': {('vacancy', 'email')},
            },
        ),
    ]
