# Generated by Django 4.2.14 on 2025-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='portfolio_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл с портфолио'),
        ),
    ]
