# Generated by Django 4.2.14 on 2025-04-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_response_portfolio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='hard_skills',
            field=models.CharField(default=1, max_length=255, verbose_name='Hard skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='soft_skills',
            field=models.CharField(default=1, max_length=255, verbose_name='Soft skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_experience',
            field=models.CharField(default=1, max_length=255, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='text',
            field=models.CharField(verbose_name='Обязанность'),
        ),
        migrations.DeleteModel(
            name='InfoBlock',
        ),
    ]
