# Generated by Django 4.2.14 on 2025-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_vacancy_hard_skills_vacancy_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['order'], 'verbose_name': 'Требование', 'verbose_name_plural': 'Требования'},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'ordering': ['order'], 'verbose_name': 'Обязанность', 'verbose_name_plural': 'Обязанности'},
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.CharField(verbose_name='Требование'),
        ),
    ]
