# Generated by Django 4.2.14 on 2025-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(default=1, max_length=150, verbose_name='Короткое описание вакансии'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Полное описание вакансии'),
        ),
    ]
