# Generated by Django 4.2.14 on 2025-04-28 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_short_description_alter_vacancy_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(verbose_name='Условие')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Положение')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сondition', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
                'ordering': ['order'],
                'unique_together': {('vacancy', 'order')},
            },
        ),
    ]
