# Generated by Django 4.2.14 on 2025-04-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary',
        ),
    ]
