# Generated by Django 4.2.14 on 2025-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contacts', 'Контакты'), ('policy', 'Политика'), ('certificates', 'Сертификаты'), ('team', 'Команда'), ('price', 'Цены'), ('briefing', 'Брифинг'), ('competencies', 'Компетенции'), ('services', 'Услуги')], max_length=20, unique=True, verbose_name='Тип сайта')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Содержание для title')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Содержание для meta(description)')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
    ]
