# Generated by Django 4.2.14 on 2025-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'SEO', 'verbose_name_plural': 'SEO'},
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, null=True, verbose_name='Содержание для meta(keywords)'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='type',
            field=models.CharField(choices=[('main', 'Главная'), ('contacts', 'Контакты'), ('policy', 'Политика'), ('certificates', 'Сертификаты'), ('team', 'Команда'), ('price', 'Цены'), ('briefing', 'Брифинг'), ('competencies', 'Компетенции'), ('services', 'Услуги')], max_length=20, unique=True, verbose_name='Страница'),
        ),
    ]
