# Generated by Django 4.2.14 on 2025-01-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_seo_options_seo_keywords_alter_seo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание для meta(description)'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание для meta(keywords)'),
        ),
    ]
