# Generated by Django 4.2.14 on 2025-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_seo_description_alter_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='type',
            field=models.CharField(choices=[('main', 'Главная'), ('contacts', 'Контакты'), ('policy', 'Политика'), ('certificates', 'Сертификаты'), ('team', 'Команда'), ('price', 'Цены'), ('briefing', 'Брифинг'), ('competencies', 'Компетенции'), ('services', 'Услуги'), ('projects', 'Проекты'), ('articles', 'Статьи')], max_length=20, unique=True, verbose_name='Страница'),
        ),
    ]
