# Generated by Django 4.2.14 on 2025-01-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_article_seo_description_and_more'),
        ('projects', '0010_alter_block_image_alter_block_text'),
        ('pages', '0004_alter_seo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Содержание для title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Содержание для meta(description)')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Содержание для meta(keywords)')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='projects.project')),
            ],
            options={
                'verbose_name': 'SEO (Статья)',
                'verbose_name_plural': 'SEO (Статьи)',
            },
        ),
        migrations.CreateModel(
            name='ArticleSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Содержание для title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Содержание для meta(description)')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Содержание для meta(keywords)')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='articles.article')),
            ],
            options={
                'verbose_name': 'SEO (Статья)',
                'verbose_name_plural': 'SEO (Статьи)',
            },
        ),
    ]
