# Generated by Django 4.2.14 on 2025-01-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_projectseo_articleseo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectseo',
            old_name='article',
            new_name='project',
        ),
    ]
