# Generated by Django 4.2.14 on 2025-04-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_article_projectseo_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SEO',
            new_name='PageSEO',
        ),
    ]
