# Generated by Django 4.2.14 on 2025-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_seo_pageseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main', 'Главная'), ('contacts', 'Контакты'), ('policy', 'Политика'), ('certificates', 'Сертификаты'), ('team', 'Команда'), ('price', 'Цены'), ('briefing', 'Брифинг'), ('competencies', 'Компетенции'), ('services', 'Услуги'), ('projects', 'Проекты'), ('articles', 'Статьи')], max_length=20, unique=True, verbose_name='Страница')),
                ('title', models.CharField(blank=True, help_text='Может отсутствовать на странице', null=True, verbose_name='Содержание заголовка')),
                ('description', models.TextField(blank=True, help_text='Может отсутствовать на странице', null=True, verbose_name='Содержание описания')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
    ]
