# Generated by Django 4.2.14 on 2025-04-22 06:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Может отсутствовать на странице', null=True, verbose_name='Содержание описания'),
        ),
    ]
