# Generated by Django 4.2.14 on 2025-04-22 10:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pagecontent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main', 'Главная'), ('services', 'Услуги')], max_length=20, unique=True, verbose_name='Страница')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Аккардеон',
                'verbose_name_plural': 'Аккордеоны',
            },
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='type',
            field=models.CharField(choices=[('main', 'Главная'), ('contacts', 'Контакты'), ('policy', 'Политика'), ('certificates', 'Сертификаты'), ('team', 'Команда'), ('price', 'Цены'), ('career', 'Карьера'), ('briefing', 'Брифинг'), ('competencies', 'Компетенции'), ('services', 'Услуги'), ('projects', 'Проекты'), ('articles', 'Статьи')], max_length=20, unique=True, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='type',
            field=models.CharField(choices=[('main', 'Главная'), ('contacts', 'Контакты'), ('policy', 'Политика'), ('certificates', 'Сертификаты'), ('team', 'Команда'), ('price', 'Цены'), ('career', 'Карьера'), ('briefing', 'Брифинг'), ('competencies', 'Компетенции'), ('services', 'Услуги'), ('projects', 'Проекты'), ('articles', 'Статьи')], max_length=20, unique=True, verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subblocks', to='pages.accordion')),
            ],
            options={
                'verbose_name': 'Элемент аккардеона',
                'verbose_name_plural': 'Элементы аккордеона',
            },
        ),
    ]
