# Generated by Django 4.2.14 on 2025-04-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_accordion_alter_pagecontent_type_alter_pageseo_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accordionitem',
            options={'ordering': ['order'], 'verbose_name': 'Элемент аккардеона', 'verbose_name_plural': 'Элементы аккордеона'},
        ),
        migrations.AlterField(
            model_name='accordionitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_items', to='pages.accordion', verbose_name='Аккардеон'),
        ),
        migrations.AlterUniqueTogether(
            name='accordionitem',
            unique_together={('parent', 'order')},
        ),
    ]
