# Generated by Django 4.2.14 on 2025-04-24 07:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_accordionitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(max_length=255, verbose_name='Текст')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('price_discount_4', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой 4%')),
                ('price_discount_6', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой 6%')),
                ('price_discount_7', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой 7%')),
                ('price_discount_12', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой 12%')),
            ],
            options={
                'verbose_name': 'Элемент таблицы цен',
                'verbose_name_plural': 'Элементы таблицы цен',
            },
        ),
        migrations.AlterModelOptions(
            name='accordion',
            options={'verbose_name': 'Аккордеон', 'verbose_name_plural': 'Аккордеоны'},
        ),
        migrations.AlterModelOptions(
            name='accordionitem',
            options={'ordering': ['order'], 'verbose_name': 'Элемент аккордеона', 'verbose_name_plural': 'Элементы аккордеона'},
        ),
        migrations.AlterField(
            model_name='accordionitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordion_items', to='pages.accordion', verbose_name='Аккордеон'),
        ),
    ]
