# Generated by Django 4.2.14 on 2025-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_price_alter_accordion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['order'], 'verbose_name': 'Элемент таблицы цен', 'verbose_name_plural': 'Элементы таблицы цен'},
        ),
        migrations.AddField(
            model_name='price',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
