# Generated by Django 4.2.14 on 2025-04-29 05:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_price_options_price_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('clients_title', models.CharField(blank=True, null=True, verbose_name='Заголовок у клиентов')),
                ('clients_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание у клиентов')),
            ],
            options={
                'verbose_name': 'Страница "Команда"',
                'verbose_name_plural': 'Страница "Команда"',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='imgs/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='pages.teampage', verbose_name='Страница команды')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
                'unique_together': {('page', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_image', to='pages.teampage', verbose_name='Страница команды')),
            ],
            options={
                'verbose_name': 'Изображение клиента',
                'verbose_name_plural': 'Изображения клиентов',
                'ordering': ['order'],
                'unique_together': {('page', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ClientFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и фамилия клиента')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='imgs/', verbose_name='Фото клиента')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_feedback', to='pages.teampage', verbose_name='Страница команды')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['order'],
                'unique_together': {('page', 'order')},
            },
        ),
    ]
