# Generated by Django 4.2.14 on 2025-04-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_teampage_team_clientimage_clientfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
    ]
