# Generated by Django 4.2.14 on 2025-04-29 06:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_team_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfeedback',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
    ]
