# Generated by Django 4.2.14 on 2025-04-29 06:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_clientfeedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='experience_of_specialists',
            field=models.CharField(default=1, max_length=20, verbose_name='Опыт специалистов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampage',
            name='number_of_experts',
            field=models.CharField(default=1, max_length=20, verbose_name='Кол-во экспертов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teampage',
            name='number_of_projects',
            field=models.CharField(default=1, max_length=20, verbose_name='Кол-во проектов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teampage',
            name='clients_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Описание у клиентов'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='clients_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок у клиентов'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
