# Generated by Django 4.2.14 on 2024-12-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.TextField(default='', max_length=200, verbose_name='Превью текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.ImageField(upload_to='articles/media/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image2',
            field=models.ImageField(upload_to='articles/mediapy/', verbose_name='Картинка в элементе'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
