# Generated by Django 4.2.14 on 2024-12-26 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image2',
        ),
        migrations.AddField(
            model_name='article',
            name='element_img',
            field=models.ImageField(default=1, upload_to='imgs/', verbose_name='Картинка в элементе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.TextField(default='', max_length=200, verbose_name='Превью текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_img',
            field=models.ImageField(default=1, upload_to='imgs/', verbose_name='Превью'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блока')),
                ('text', models.TextField(verbose_name='Текст блока')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moderation', to='articles.article', verbose_name='Блок статьи')),
            ],
        ),
    ]
