# Generated by Django 4.2.14 on 2024-12-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_preview_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блока')),
                ('text', models.TextField(verbose_name='Текст блока')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image2',
        ),
        migrations.AddField(
            model_name='article',
            name='element_img',
            field=models.ImageField(default=1, upload_to='imgs/', verbose_name='Картинка в элементе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='preview_img',
            field=models.ImageField(default=1, upload_to='imgs/', verbose_name='Превью'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='txt_block',
            field=models.ManyToManyField(to='articles.contentblock', verbose_name='Блок с текстом'),
        ),
    ]
