# Generated by Django 4.2.14 on 2024-12-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_content_remove_article_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
    ]
