# Generated by Django 4.2.14 on 2024-12-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_contentblock_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='Положение'),
            preserve_default=False,
        ),
    ]
