# Generated by Django 4.2.14 on 2024-12-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_contentblock_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Положение'),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('article', 'order')},
        ),
    ]
