# Generated by Django 4.2.14 on 2025-01-09 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_contentblock_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_block', to='articles.article', verbose_name='Статья'),
        ),
    ]
