# Generated by Django 4.2.14 on 2025-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_theme_article_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Символьный код'),
        ),
    ]
