# Generated by Django 4.2.14 on 2025-01-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Символьный код'),
        ),
    ]
