# Generated by Django 4.2.14 on 2025-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Символьный код'),
        ),
    ]
