# Generated by Django 4.2.14 on 2025-01-24 11:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_article_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст блока'),
        ),
    ]
