# Generated by Django 4.2.14 on 2025-01-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_contentblock_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание для meta(description)'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание для meta(keywords)'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, null=True, verbose_name='Содержание для title'),
        ),
    ]
