# Generated by Django 4.2.14 on 2025-01-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_article_seo_description_article_seo_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='seo_title',
        ),
    ]
